/*
Write a C program which will create child processes in the following tree format. Make sure that the output of print statement generated by various child and parent processes strictly followed any one of the following  sequence.
parent 1 has child 1 and child 2 as kids.child 2 has child 3 and child 4 as kids

Output:
Child 3 My id is ___ and my parent id is _____.
Child 4 My id is ___ and my parent id is _____.
Child 2 My id is ___ and my parent id is _____.
Child 1 My id is ___ and my parent id is _____.
Parent Process my id is ___ and my parent id is _____.

or

Child 4 My id is ___ and my parent id is _____.
Child 3 My id is ___ and my parent id is _____.
Child 2 My id is ___ and my parent id is _____.
Child 1 My id is ___ and my parent id is _____.
Parent Process my id is ___ and my parent id is _____.

or

Child 1 My id is ___ and my parent id is _____.
Child 3 My id is ___ and my parent id is _____.
Child 4 My id is ___ and my parent id is _____.
Child 2 My id is ___ and my parent id is _____.
Parent Process my id is ___ and my parent id is _____.

or

Child 1 My id is ___ and my parent id is _____.
Child 4 My id is ___ and my parent id is _____.
Child 3 My id is ___ and my parent id is _____.
Child 2 My id is ___ and my parent id is _____.
Parent Process my id is ___ and my parent id is ____.
*/

#include<stdio.h>
#include<stdlib.h>
#include<unistd.h>
#include<sys/wait.h>

void printinfo(int id)
{
    printf("child %d My id is %d and my parent id is %d.\n",id,getpid(),getppid());
}

int main()
{
    int n=4;//no.of child processes ie no.of nodes-1
    
    printf("Parent Process my id id %d and my parent id is %d.\n",getpid(),getppid());
    
    for(int i=1;i<=n;i++)
    {
        pid_t pid=fork();
        
        if(pid<0)
        {
            perror("Fork Failed");
            exit(1);
        }
        else if(pid ==0)
        {
            //child process
            printinfo(i);
            
            //if its child 2,create two more process
            if(i==2)
            {
                for(int j=3;j<=4;j++)
                {
                    pid_t child_pid=fork();
                    if(child_pid<0)
                    {
                        perror("fork failed");
                        exit(1);
                    }
                    else if(child_pid==0)
                    {
                        printinfo(j);
                        exit(0);
                    }
                }
            }
            exit(0);
        }
        else
        {
            //parent
            wait(NULL);
        }
    }
    return 0;
}